on:
  pull_request:
  push:
    branches:
      - master
name: ci
jobs:
  format:
    name: Format ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'master' }}
          fetch-depth: 0
      - name: Test
        run:  ls -la
      - name: Terraform fmt
        run:  docker run -v "$PWD":/mnt -w /mnt hashicorp/terraform:$(cat .terraform-version) fmt
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
