on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: write
name: ci
jobs:
  format:
    name: Format ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || 'master' }}
          fetch-depth: 0
      
      - name: Terraform fmt
        run:  ci/format-tf.sh

      - name: Generate Terraform docs
        run: ci/generate-tf-docs.sh

      - name: Push changes back to branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: formatting and documentation"
          git push
